-- ============================================================
-- AI-Ready Data Demo: Support Knowledge Base — Create Tables
-- ============================================================
-- Scenario: Your company runs a support portal backed by a
-- knowledge base in Snowflake. The data has been here for
-- months — migrated from a legacy wiki, augmented with a
-- chunking pipeline, and linked to a CRM and ticketing system.
--
-- Now the team wants to build a RAG-powered search tool with
-- Cortex Search. The question is: is the data ready?
--
-- Uses SNOWFLAKE_LEARNING_DB (pre-provisioned in every
-- Snowflake account). Requires SNOWFLAKE_LEARNING_ADMIN_ROLE.
--
-- Run this first, then 02-load-data.sql, then 03-brownfield.sql.
-- ============================================================

USE ROLE SNOWFLAKE_LEARNING_ADMIN_ROLE;
USE DATABASE SNOWFLAKE_LEARNING_DB;

CREATE SCHEMA IF NOT EXISTS SUPPORT_KB;
USE SCHEMA SUPPORT_KB;

-- ============================================================
-- ARTICLES — Knowledge base articles
-- ============================================================
-- Migrated from a legacy Confluence wiki 6 months ago.
-- The wiki had inconsistent metadata — many articles had no
-- author or category because the old system didn't require them.
CREATE OR REPLACE TABLE ARTICLES (
    article_id      NUMBER,
    title           VARCHAR(500),
    body            VARCHAR(16000),
    author          VARCHAR(200),
    category        VARCHAR(100),
    status          VARCHAR(50),
    created_at      TIMESTAMP_NTZ,
    updated_at      TIMESTAMP_NTZ
);

-- ============================================================
-- ARTICLE_CHUNKS — Pre-chunked content for embedding
-- ============================================================
-- Generated by a Python chunking pipeline that ran over all
-- articles. The pipeline crashed on some HTML-heavy articles
-- and produced empty chunks instead of failing cleanly.
CREATE OR REPLACE TABLE ARTICLE_CHUNKS (
    chunk_id        NUMBER,
    article_id      NUMBER,
    chunk_text      VARCHAR(8000),
    chunk_index     NUMBER,
    token_count     NUMBER
);

-- ============================================================
-- CUSTOMERS — Customer records (contains PII)
-- ============================================================
-- Synced nightly from the CRM. Some records are phone-only
-- leads from trade shows; others are web signups with email
-- but no phone. PII columns have NO masking policies.
CREATE OR REPLACE TABLE CUSTOMERS (
    customer_id     NUMBER,
    full_name       VARCHAR(200),
    email           VARCHAR(300),
    phone           VARCHAR(50),
    address         VARCHAR(500),
    company         VARCHAR(200),
    plan_tier       VARCHAR(50),
    created_at      TIMESTAMP_NTZ
);

-- ============================================================
-- SUPPORT_TICKETS — Tickets linked to articles and customers
-- ============================================================
-- From the ticketing system. Most tickets were never linked to
-- a KB article (article_id is null). Open and in-progress
-- tickets intentionally have no resolved_at — that's correct,
-- not a quality issue.
CREATE OR REPLACE TABLE SUPPORT_TICKETS (
    ticket_id       NUMBER,
    subject         VARCHAR(500),
    description     VARCHAR(8000),
    customer_id     NUMBER,
    article_id      NUMBER,
    status          VARCHAR(50),
    priority        VARCHAR(20),
    created_at      TIMESTAMP_NTZ,
    resolved_at     TIMESTAMP_NTZ
);
